### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by iboldurev** [ShowJoy/element-helper#1]
Atom version: 1.18.0
element-helper: 0.3.2

![2017-07-06 18 57 12](https://user-images.githubusercontent.com/17103170/27920352-f30aa59e-627c-11e7-934d-fa4e6e6ab723.png)

Please help

**Comment by ShowJoy** [comment]
you should start with character '<'

**Comment by ShowJoy** [comment]
any question, you can pull issue to our [TEAM](https://github.com/ElemeFE/element-helper),  maybe solve your question much faster.
